import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>
                <Toaster
                    position="top-right"
                    reverseOrder={false}
                    toastOptions={{
                        success: {
                            style: {
                                borderRadius: "var(--radius)",
                                backgroundColor: "hsl(var(--card))",
                                color: "hsl(var(--card-foreground))",
                            },
                        },
                        error: {
                            style: {
                                borderRadius: "var(--radius)",
                                backgroundColor: "hsl(var(--card))",
                                color: "hsl(var(--card-foreground))",
                            },
                        },
                    }}
                />
            </body>
        </html>
    );
}
